# главный роут
app:
    path: /{_locale}
    defaults: { _controller: AppBundle:Default:index, _locale: '%locale%' }
    requirements:
        _locale: '%available_langs%'

login:
    path:   /{_locale}/login
    defaults:  { _controller: AppBundle:User:login, _locale: '%locale%' }
    requirements:
        _locale: '%available_langs%'

login_check:
    path:   /login_check

adminka.home:
    path: /adminka
    defaults: { _controller: AppBundle:Admin/DashboardAdm:index, _locale: '%locale%' }
    requirements:
        _locale: '%available_langs%'

# роуты по юзерам
adminka.user.list:
    path: /adminka/users
    defaults: { _controller: AppBundle:Admin/UsersAdm:list, id: null, _locale: '%locale%' }
    requirements:
        _locale: '%available_langs%'

adminka.user.update:
    path: /adminka/user/{id}/update
    defaults: { _controller: AppBundle:Admin/UsersAdm:update, _locale: '%locale%' }
    requirements:
        _locale: '%available_langs%'
        id: \d+

adminka.user.edit:
    path: /adminka/user/{id}/edit
    defaults: { _controller: AppBundle:Admin/UsersAdm:edit, _locale: '%locale%' }
    requirements:
        _locale: '%available_langs%'
        id: \d+

adminka.user.delete:
    path: /adminka/user/{id}/del
    defaults: { _controller: AppBundle:Admin/UsersAdm:delete, _locale: '%locale%' }
    requirements:
        _locale: '%available_langs%'
        id: \d+